# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='b2b_client_dept_percentage',
            fields=[
                ('dept_per_id', models.BigAutoField(default=1033550000000, editable=False, primary_key=True, serialize=False)),
                ('b2b_dept_perc', models.IntegerField(blank=True, null=True)),
                ('b2b_dept_amt', models.IntegerField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1451000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1385100000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='b2b_client_item_percentage',
            fields=[
                ('item_per_id', models.BigAutoField(default=1022550000000, editable=False, primary_key=True, serialize=False)),
                ('b2b_item_perc', models.IntegerField(blank=True, null=True)),
                ('b2b_item_amt', models.IntegerField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1961000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1985100000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='b2b_client_item_rates',
            fields=[
                ('b2b_clitr_id', models.BigAutoField(default=1133440000000, editable=False, primary_key=True, serialize=False)),
                ('b2b_client_rate', models.IntegerField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1877000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1556600000000, editable=False, null=True)),
            ],
        ),
    ]
