# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b2b_clients_management', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2b_client_item_rates',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2b2bclir_id', to='organizations.organizationlst'),
        ),
    ]
