# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_setup', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_setup', '0001_initial'),
        ('department', '0002_initial'),
        ('b2b_clients_management', '0003_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2b_client_item_rates',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2b2bclir_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2b_client_item_rates',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2b2bclir_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2b_client_item_rates',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2b2bclir_id', to='supplier_setup.suppliers'),
        ),
        migrations.AddField(
            model_name='b2b_client_item_percentage',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2b2bitem_perc', to='item_setup.items'),
        ),
        migrations.AddField(
            model_name='b2b_client_item_percentage',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2b2bitem_perc', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='b2b_client_item_percentage',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2b2bitem_perc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2b_client_item_percentage',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2b2bitem_perc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2b_client_item_percentage',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2b2bitem_perc', to='supplier_setup.suppliers'),
        ),
        migrations.AddField(
            model_name='b2b_client_dept_percentage',
            name='dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dept_id2b2bdept_perc', to='department.departmentlst'),
        ),
        migrations.AddField(
            model_name='b2b_client_dept_percentage',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2b2bdept_perc', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='b2b_client_dept_percentage',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2b2bdept_perc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2b_client_dept_percentage',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2b2bdept_perc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2b_client_dept_percentage',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2b2bdept_perc', to='supplier_setup.suppliers'),
        ),
    ]
