# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup_modes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uitemplate_setup',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2uitemp_setup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uitemplate_setup',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2uitemp_setup', to=settings.AUTH_USER_MODEL),
        ),
    ]
