# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('manufac_id', models.BigAutoField(default=123010000000, editable=False, primary_key=True, serialize=False)),
                ('manufac_no', models.CharField(max_length=100, unique=True)),
                ('manufac_name', models.CharField(max_length=200, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('manufacturer_flag', models.BooleanField(default=False)),
                ('foreign_flag', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('manufac_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manufac_fax', models.CharField(blank=True, max_length=100, null=True)),
                ('manufac_web', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('manufac_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('con_per_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1230000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112300000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('supplier_id', models.BigAutoField(default=122090000000, editable=False, primary_key=True, serialize=False)),
                ('supplier_no', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('supplier_flag', models.IntegerField(blank=True, default=0, null=True)),
                ('manufacturer_flag', models.IntegerField(blank=True, default=0, null=True)),
                ('b2bclient_flag', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supplier_fax', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_web', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('con_per_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1230000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112300000000, editable=False, null=True)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2suppliers', to='organizations.organizationlst')),
            ],
        ),
    ]
