# Generated by Django 4.1.5 on 2024-10-19 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemShutdown',
            fields=[
                ('sys_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sys_shut_down_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('sys_down_time_validity', models.DateTimeField()),
                ('is_sys_shut_down', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2sys_shutd', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2sys_shutd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
