# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='po_return_details',
            fields=[
                ('poretdtl_id', models.BigAutoField(default=5510000000000, editable=False, primary_key=True, serialize=False)),
                ('return_qty', models.IntegerField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('returned_date', models.CharField(blank=True, max_length=150, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=4401000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=44011000000, editable=False, null=True)),
            ],
        ),
    ]
