# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='in_bill_templates',
            fields=[
                ('btemp_id', models.BigAutoField(default=1099900000000, editable=False, primary_key=True, serialize=False)),
                ('btemp_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1088400000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=107750000000, editable=False, null=True)),
            ],
        ),
    ]
