# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_setup', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_lists',
            name='bank_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_branch2banklists', to='user_setup.lookup_values'),
        ),
        migrations.AddField(
            model_name='bank_lists',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2banklists', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='bank_lists',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='country2banklists', to='user_setup.lookup_values'),
        ),
        migrations.AddField(
            model_name='bank_lists',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='district2banklists', to='user_setup.lookup_values'),
        ),
        migrations.AddField(
            model_name='bank_lists',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='division2banklists', to='user_setup.lookup_values'),
        ),
        migrations.AddField(
            model_name='bank_lists',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2banklists', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='bank_lists',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2banklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank_lists',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2banklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bank_lists',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='upazila2banklists', to='user_setup.lookup_values'),
        ),
    ]
