# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_setup', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_order_list',
            fields=[
                ('po_id', models.BigAutoField(default=2210000000000, editable=False, primary_key=True, serialize=False)),
                ('po_no', models.CharField(editable=False, max_length=15)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('is_credit', models.BooleanField(default=False)),
                ('is_cash', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('received_date', models.CharField(blank=True, max_length=50, null=True)),
                ('returned_date', models.CharField(blank=True, max_length=50, null=True)),
                ('return_received_date', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_returned', models.BooleanField(default=False)),
                ('is_return_received', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='', max_length=300)),
                ('received_remarks', models.TextField(blank=True, default='', max_length=300)),
                ('returned_remarks', models.TextField(blank=True, default='', max_length=300)),
                ('return_received_remarks', models.TextField(blank=True, default='', max_length=300)),
                ('dis_percentance', models.IntegerField(blank=True, null=True)),
                ('vat_percentance', models.IntegerField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1101000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=120950000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_orderdtls',
            fields=[
                ('podtl_id', models.BigAutoField(default=3311000000000, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('order_qty', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=3291000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=312950000000, editable=False, null=True)),
                ('item_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2podtls', to='item_setup.items')),
                ('po_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='po_id2podtls', to='purchase_order.purchase_order_list')),
            ],
        ),
    ]
