# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_setup', '0001_initial'),
        ('purchase_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_setup', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_orderdtls',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2podtls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_orderdtls',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2podtls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_orderdtls',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2podtls', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2polist', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='id_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2polist', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='is_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2is_appr_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='is_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2is_rec_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='is_return_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2is_retu_rec_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='is_returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2is_retu_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2polist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2polist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2polist', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='purchase_order_list',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2polist', to='supplier_setup.suppliers'),
        ),
    ]
