# Generated by Django 4.1.5 on 2024-10-18 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_setup', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_reconciliation',
            fields=[
                ('recon_id', models.BigAutoField(default=1234300000000, editable=False, primary_key=True, serialize=False)),
                ('recon_no', models.CharField(editable=False, max_length=15)),
                ('recon_type', models.IntegerField(blank=True, null=True)),
                ('recon_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('approved_date', models.DateField(blank=True, editable=False, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1456000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=103060000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_reconciliationdtl',
            fields=[
                ('recondtl_id', models.BigAutoField(default=1553000000000, editable=False, primary_key=True, serialize=False)),
                ('recondtl_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateField(blank=True, editable=False, null=True)),
                ('recon_qty', models.CharField(blank=True, max_length=150, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1053000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=104210000000, editable=False, null=True)),
                ('item_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2recondtl', to='item_setup.items')),
                ('recon_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recon_id_id', to='stock_reconciliation.item_reconciliation')),
            ],
        ),
    ]
