# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_setup', '0001_initial'),
        ('stock_reconciliation', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_reconciliationdtl',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2recondtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_reconciliationdtl',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2recondtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_reconciliationdtl',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2recondtl', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='item_reconciliation',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2recon', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='item_reconciliation',
            name='id_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2recon', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='item_reconciliation',
            name='is_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2recon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_reconciliation',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2recon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_reconciliation',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2recon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_reconciliation',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2recon', to='store_setup.store'),
        ),
    ]
