# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_setup', '0001_initial'),
        ('G_R_N_with_without', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='without_grndtl',
            name='item_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2wo_grnDtl', to='item_setup.items'),
        ),
    ]
