# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('G_R_N_with_without', '0002_initial'),
        ('supplier_setup', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='without_grndtl',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2wo_grnDtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='without_grndtl',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2wo_grnDtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='without_grndtl',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2wo_grnDtl', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='without_grndtl',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2wo_grnDtl', to='supplier_setup.suppliers'),
        ),
        migrations.AddField(
            model_name='without_grndtl',
            name='wo_grn_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='without_grn_id', to='G_R_N_with_without.without_grn'),
        ),
        migrations.AddField(
            model_name='without_grn',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2wo_grn', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='without_grn',
            name='id_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2wo_grn', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='without_grn',
            name='is_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2wo_grn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='without_grn',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2wo_grn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='without_grn',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2wo_grn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='without_grn',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2wo_grn', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='without_grn',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2wo_grn', to='supplier_setup.suppliers'),
        ),
    ]
