# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='po_receive_details',
            fields=[
                ('pordtl_id', models.BigAutoField(default=4410000000000, editable=False, primary_key=True, serialize=False)),
                ('receive_qty', models.FloatField(blank=True, null=True)),
                ('bonus_qty', models.FloatField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('received_date', models.CharField(blank=True, max_length=150, null=True)),
                ('item_batch', models.CharField(blank=True, max_length=150, null=True)),
                ('item_exp_date', models.DateField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=3301000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=33011000000, editable=False, null=True)),
            ],
        ),
    ]
