# Generated by Django 4.1.5 on 2024-10-18 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_Chalan_list',
            fields=[
                ('chalan_id', models.BigAutoField(default=1000000011000, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('is_created', models.BooleanField(default=False)),
                ('is_update', models.BooleanField(default=False)),
                ('is_modified_item', models.BooleanField(default=False)),
                ('is_out_sourceing', models.BooleanField(default=False)),
                ('is_direct_or_hold', models.BooleanField(default=False)),
                ('is_hold_approve', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1277800008000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112888001000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='delivery_Chalandtl_list',
            fields=[
                ('chanaldtl_id', models.BigAutoField(default=2223400000000, editable=False, primary_key=True, serialize=False)),
                ('del_chalan_date', models.DateField(blank=True, null=True)),
                ('deliver_qty', models.FloatField(blank=True, default=0)),
                ('is_out_sourceing', models.BooleanField(blank=True, default=False)),
                ('is_direct_or_hold', models.BooleanField(blank=True, default=False)),
                ('is_hold_approve', models.BooleanField(blank=True, default=False)),
                ('is_extra_item', models.BooleanField(blank=True, default=False, null=True)),
                ('is_update', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1667900000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=778910000000, editable=False, null=True)),
                ('chalan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deliver_chalan.delivery_chalan_list')),
            ],
        ),
    ]
