# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_setup', '0001_initial'),
        ('item_pos', '0002_initial'),
        ('deliver_chalan', '0001_initial'),
        ('item_setup', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_chalandtl_list',
            name='deliver_store',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver_store2chalandtl', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='delivery_chalandtl_list',
            name='inv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inv_id2chalandtl', to='item_pos.invoice_list'),
        ),
        migrations.AddField(
            model_name='delivery_chalandtl_list',
            name='invdtl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invdtl_id2chalandtl', to='item_pos.invoicedtl_list'),
        ),
        migrations.AddField(
            model_name='delivery_chalandtl_list',
            name='item_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2chalandtl', to='item_setup.items'),
        ),
    ]
