# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_pos', '0002_initial'),
        ('deliver_chalan', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_chalandtl_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2chalandtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_chalandtl_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2chalandtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_chalan_list',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2chalan', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='delivery_chalan_list',
            name='inv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inv_id2chalan', to='item_pos.invoice_list'),
        ),
        migrations.AddField(
            model_name='delivery_chalan_list',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2chalan', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='delivery_chalan_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2chalan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery_chalan_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2chalan', to=settings.AUTH_USER_MODEL),
        ),
    ]
