# Generated by Django 4.1.5 on 2024-10-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_chalan', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_chalandtl_list',
            name='is_cancel_qty',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
