# Generated by Django 4.1.5 on 2024-10-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchslist',
            name='is_main_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchslist',
            name='is_sub_branch',
            field=models.BooleanField(default=False),
        ),
    ]
