# Generated by Django 4.1.5 on 2024-06-21 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_list',
            fields=[
                ('inv_id', models.BigAutoField(default=1000110010000, editable=False, primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('is_general_bill', models.BooleanField(default=False)),
                ('is_b2b_clients', models.BooleanField(default=False)),
                ('is_non_register', models.BooleanField(default=False)),
                ('is_register', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('road_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sector_no', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('referral_person', models.CharField(blank=True, max_length=100, null=True)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1266000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112670000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoicedtl_list',
            fields=[
                ('invdtl_id', models.BigAutoField(default=1100000000000, editable=False, primary_key=True, serialize=False)),
                ('qty', models.BigIntegerField(blank=True, default=0)),
                ('sales_rate', models.FloatField(blank=True, default=0)),
                ('item_w_dis', models.FloatField(blank=True, default=0)),
                ('gross_dis', models.FloatField(blank=True, default=0)),
                ('gross_vat_tax', models.FloatField(blank=True, default=0)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_cancel_qty', models.BigIntegerField(blank=True, default=0)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=200)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1268000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112690000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment_list',
            fields=[
                ('pay_id', models.BigAutoField(default=1110000000000, editable=False, primary_key=True, serialize=False)),
                ('pay_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('pay_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('collection_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('pay_amt', models.FloatField(blank=True, default=0)),
                ('given_amt', models.FloatField(blank=True, default=0)),
                ('change_amt', models.FloatField(blank=True, default=0)),
                ('card_info', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_mob_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1271000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112720000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rent_others_exps',
            fields=[
                ('other_exps_id', models.BigAutoField(default=1321000000000, editable=False, primary_key=True, serialize=False)),
                ('other_exps_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('other_exps_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_buyer', models.BooleanField(default=False)),
                ('other_exps_amt', models.FloatField(blank=True, default=0)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1575000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=137720000000, editable=False, null=True)),
            ],
        ),
    ]
