# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0001_initial'),
        ('stock_list', '0002_initial'),
        ('item_setup', '0002_initial'),
        ('store_setup', '0001_initial'),
        ('drivers_setup', '0003_initial'),
        ('item_pos', '0002_initial'),
        ('organizations', '0001_initial'),
        ('supplier_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_others_exps',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2other_exps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rent_others_exps',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2other_exps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment_list',
            name='inv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_pos.invoice_list'),
        ),
        migrations.AddField(
            model_name='payment_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_fav_list',
            name='item_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2item_fav_list', to='item_setup.items'),
        ),
        migrations.AddField(
            model_name='item_fav_list',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2item_fav_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicedtl_list',
            name='inv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_pos.invoice_list'),
        ),
        migrations.AddField(
            model_name='invoicedtl_list',
            name='item_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2invoicedtl', to='item_setup.items'),
        ),
        migrations.AddField(
            model_name='invoicedtl_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2invoicedtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicedtl_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2invoicedtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicedtl_list',
            name='stock_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_id2invoicedtl', to='stock_list.stock_lists'),
        ),
        migrations.AddField(
            model_name='invoicedtl_list',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2invoicedtl', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2invoice', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='cash_point',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2invoice', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='driver_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_id2invoice', to='drivers_setup.drivers_list'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2invoice', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='reg_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2invoice', to='registrations.in_registrations'),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2invoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2invoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='supplier_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2invoice', to='supplier_setup.suppliers'),
        ),
    ]
