# Generated by Django 4.1.5 on 2024-10-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_pos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_list',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invoicedtl_list',
            name='uom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
