# Generated by Django 4.1.5 on 2024-10-23 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_order', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_setup', '0002_initial'),
        ('item_setup', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lp_return_details',
            fields=[
                ('lprdtl_id', models.BigAutoField(default=6677100000000, editable=False, primary_key=True, serialize=False)),
                ('lp_return_qty', models.FloatField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('returned_date', models.CharField(blank=True, max_length=150, null=True)),
                ('item_batch', models.CharField(blank=True, max_length=150, null=True)),
                ('item_exp_date', models.DateField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=9916700000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=2267809000000, editable=False, null=True)),
                ('is_returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2lprdtl', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2lprdtl', to='item_setup.items')),
                ('lp_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='po_id2lprdtl', to='purchase_order.purchase_order_list')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2lprdtl', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2lprdtl', to=settings.AUTH_USER_MODEL)),
                ('store_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2lprdtl', to='store_setup.store')),
            ],
        ),
    ]
