# Generated by Django 4.1.5 on 2024-10-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_purchase_return', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lp_return_details',
            name='is_cancel_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
