# Generated by Django 4.1.5 on 2024-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_purchase_return', '0002_lp_return_details_is_cancel_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='lp_return_details',
            name='returned_remarks',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
