# Generated by Django 4.1.5 on 2024-10-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_purchase', '0004_local_purchase_is_returned_and_more'),
        ('local_purchase_return', '0003_lp_return_details_returned_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_return_details',
            name='lp_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_id2lprdtl', to='local_purchase.local_purchase'),
        ),
    ]
