# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_order', '0001_initial'),
        ('local_purchase', '0002_initial'),
        ('po_return_receive', '0001_initial'),
        ('item_setup', '0002_initial'),
        ('po_return', '0001_initial'),
        ('po_receive', '0001_initial'),
        ('opening_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_stock',
            fields=[
                ('in_stock_id', models.BigAutoField(default=111011000000, editable=False, primary_key=True, serialize=False)),
                ('stock_qty', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='stock_lists',
            fields=[
                ('stock_id', models.BigAutoField(default=112300000000, editable=False, primary_key=True, serialize=False)),
                ('recon_type', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_qty', models.FloatField(blank=True, default=0)),
                ('item_batch', models.CharField(blank=True, max_length=150, null=True)),
                ('item_exp_date', models.DateField(blank=True, null=True)),
                ('stock_date', models.DateField(auto_now=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1291000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112950000000, editable=False, null=True)),
                ('item_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2stock_lists', to='item_setup.items')),
                ('lp_dtl_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_dtl_id2stock_lists', to='local_purchase.local_purchasedtl')),
                ('lp_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lp_id2stock_lists', to='local_purchase.local_purchase')),
                ('op_st_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='op_st_id2stock_lists', to='opening_stock.opening_stock')),
                ('op_stdtl_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='op_stdtl_id2stock_lists', to='opening_stock.opening_stockdtl')),
                ('po_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='po_id2stock_lists', to='purchase_order.purchase_order_list')),
                ('pordtl_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pordtl_id2stock_lists', to='po_receive.po_receive_details')),
                ('poretdtl_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='poretdtl_id2stock_lists', to='po_return.po_return_details')),
                ('porrecdtl_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='porrecdtl_id2stock_lists', to='po_return_receive.po_return_received_details')),
            ],
        ),
    ]
