# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_setup', '0001_initial'),
        ('G_R_N_with_without', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_lists',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2stock_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock_lists',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2stock_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock_lists',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2stock_lists', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='stock_lists',
            name='wo_grn_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_grn_id2stock_lists', to='G_R_N_with_without.without_grn'),
        ),
        migrations.AddField(
            model_name='stock_lists',
            name='wo_grndtl_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_grndtl_id2stock_lists', to='G_R_N_with_without.without_grndtl'),
        ),
    ]
