# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock_list', '0001_initial'),
        ('stock_reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_lists',
            name='recon_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recon_id2stock_lists', to='stock_reconciliation.item_reconciliation'),
        ),
        migrations.AddField(
            model_name='stock_lists',
            name='recondtl_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recondtl_id2stock_lists', to='stock_reconciliation.item_reconciliationdtl'),
        ),
    ]
