# Generated by Django 4.1.5 on 2024-10-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manual_return_receive', '0001_initial'),
        ('stock_list', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_lists',
            name='manu_ret_rec_dtl_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manu_ret_rec_dtl_id2stock_lists', to='manual_return_receive.manual_return_receivedtl'),
        ),
        migrations.AddField(
            model_name='stock_lists',
            name='manu_ret_rec_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manu_ret_rec_id2stock_lists', to='manual_return_receive.manual_return_receive'),
        ),
    ]
