# Generated by Django 4.1.5 on 2024-10-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_purchase_return', '0002_lp_return_details_is_cancel_qty'),
        ('stock_list', '0004_stock_lists_manu_ret_rec_dtl_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_lists',
            name='is_cancel_qty',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='stock_lists',
            name='lprdtl_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lprdtl_id2stock_lists', to='local_purchase_return.lp_return_details'),
        ),
    ]
