# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feature_list',
            fields=[
                ('feature_id', models.BigAutoField(default=11100000001, editable=False, primary_key=True, serialize=False)),
                ('feature_no', models.CharField(blank=True, max_length=50, null=True)),
                ('feature_name', models.CharField(blank=True, max_length=150, null=True)),
                ('feature_type', models.CharField(blank=True, max_length=10, null=True)),
                ('serial_no', models.BigIntegerField(blank=True, null=True)),
                ('feature_code', models.CharField(blank=True, max_length=50, null=True)),
                ('feature_page_link', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1111000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=111200000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='module_list',
            fields=[
                ('module_id', models.BigAutoField(default=10000000001, editable=False, primary_key=True, serialize=False)),
                ('module_no', models.CharField(blank=True, max_length=50, null=True)),
                ('module_name', models.CharField(blank=True, max_length=150, null=True)),
                ('module_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1200000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=110000000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='module_type',
            fields=[
                ('type_id', models.BigAutoField(default=10100000001, editable=False, primary_key=True, serialize=False)),
                ('type_no', models.CharField(blank=True, max_length=50, null=True)),
                ('type_name', models.CharField(blank=True, max_length=150, null=True)),
                ('type_code', models.CharField(blank=True, max_length=50, null=True)),
                ('type_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1201000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=110100000000, editable=False, null=True)),
                ('module_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_id2moduletype', to='module_setup.module_list')),
            ],
        ),
    ]
