# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module_type',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2module_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module_type',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2module_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2module_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2module_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature_list',
            name='module_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_id2feature_list', to='module_setup.module_list'),
        ),
        migrations.AddField(
            model_name='feature_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2feature_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2feature_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature_list',
            name='type_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_id2feature_list', to='module_setup.module_type'),
        ),
    ]
