# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('store_id', models.BigAutoField(default=123100000000, editable=False, primary_key=True, serialize=False)),
                ('store_no', models.CharField(blank=True, max_length=50, null=True)),
                ('store_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_org_store', models.BooleanField(default=False)),
                ('is_branch_store', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_general_store', models.BooleanField(default=False)),
                ('is_main_store', models.BooleanField(default=False)),
                ('is_sub_store', models.BooleanField(default=False)),
                ('is_pos_report', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1231000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112350000000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2store', to='organizations.branchslist')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2store', to='organizations.organizationlst')),
            ],
        ),
    ]
