# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credit_transactions',
            fields=[
                ('credit_id', models.BigAutoField(default=1122330000000, editable=False, primary_key=True, serialize=False)),
                ('credit_payment', models.IntegerField(blank=True, null=True)),
                ('is_debited', models.BooleanField(default=False)),
                ('is_credited', models.BooleanField(default=False)),
                ('credit_pay_date', models.DateField(auto_now_add=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1888000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1889900000000, editable=False, null=True)),
            ],
        ),
    ]
