# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('credit_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_transactions',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2credit_trans', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='credit_transactions',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2credit_trans', to='organizations.organizationlst'),
        ),
    ]
