# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_transactions',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2credit_trans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credit_transactions',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2credit_trans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credit_transactions',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2credit_trans', to='supplier_setup.suppliers'),
        ),
    ]
