# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='po_return_received_details',
            fields=[
                ('porrecdtl_id', models.BigAutoField(default=6610000000000, editable=False, primary_key=True, serialize=False)),
                ('ret_rec_qty', models.IntegerField(blank=True, null=True)),
                ('is_return_received', models.BooleanField(default=False)),
                ('return_received_date', models.CharField(blank=True, max_length=150, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=5501000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=5501100000000, editable=False, null=True)),
            ],
        ),
    ]
