# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opening_balance',
            fields=[
                ('opb_id', models.BigAutoField(default=3088000000000, editable=False, primary_key=True, serialize=False)),
                ('opb_amount', models.FloatField(blank=True, null=True)),
                ('is_debited', models.BooleanField(default=False)),
                ('is_credited', models.BooleanField(default=False)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('opb_date', models.DateField(auto_now_add=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1099990000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1077778000000, editable=False, null=True)),
            ],
        ),
    ]
