# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients_transection', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening_balance',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2opbalance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opening_balance',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2opbalance', to=settings.AUTH_USER_MODEL),
        ),
    ]
