# Generated by Django 4.1.5 on 2024-10-30 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branchslist_is_main_branch_branchslist_is_sub_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0002_initial'),
        ('clients_transection', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentsdtls',
            fields=[
                ('pay_id', models.BigAutoField(default=1142340000000, editable=False, primary_key=True, serialize=False)),
                ('pay_date', models.DateField(auto_now_add=True)),
                ('pay_amount', models.FloatField(blank=True, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_mode', models.CharField(blank=True, max_length=4, null=True)),
                ('pay_type', models.CharField(blank=True, max_length=4, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('card_info', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_mob_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pay_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1030950000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1025875000000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2paydtls', to='organizations.branchslist')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2paydtls', to='organizations.organizationlst')),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2paydtls', to='registrations.in_registrations')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2paydtls', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2paydtls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
