# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='opening_stock',
            fields=[
                ('op_st_id', models.BigAutoField(default=1239010000000, editable=False, primary_key=True, serialize=False)),
                ('op_no', models.CharField(editable=False, max_length=15)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='', max_length=300)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1291000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112950000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opening_stockdtl',
            fields=[
                ('op_stdtl_id', models.BigAutoField(default=12400000000, editable=False, primary_key=True, serialize=False)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('op_item_qty', models.CharField(blank=True, max_length=150, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('item_batch', models.CharField(blank=True, max_length=150, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1291000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112950000000, editable=False, null=True)),
                ('item_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2opening_stockdtl', to='item_setup.items')),
                ('op_st_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opening_stock_id', to='opening_stock.opening_stock')),
            ],
        ),
    ]
