# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('store_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opening_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening_stockdtl',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2opening_stockdtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opening_stockdtl',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2opening_stockdtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opening_stockdtl',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2opening_stockdtl', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='opening_stock',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2opst', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='opening_stock',
            name='id_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2opst', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='opening_stock',
            name='is_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2opst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opening_stock',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2opst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opening_stock',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2opst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opening_stock',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2opst', to='store_setup.store'),
        ),
    ]
