# Generated by Django 4.1.5 on 2024-10-21 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0002_initial'),
        ('item_setup', '0003_initial'),
        ('store_setup', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manual_return_receive',
            fields=[
                ('manu_ret_rec_id', models.BigAutoField(default=9909099100000, editable=False, primary_key=True, serialize=False)),
                ('manu_ret_rec_no', models.CharField(editable=False, max_length=15)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_credit', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='', max_length=300)),
                ('cus_clients_name', models.CharField(blank=True, max_length=250, null=True)),
                ('cus_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cus_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('cus_emrg_person', models.CharField(blank=True, max_length=250, null=True)),
                ('cus_emrg_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('cus_address', models.CharField(blank=True, max_length=500, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1008888000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1009921000000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2manu_ter_rec', to='organizations.branchslist')),
                ('id_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2manu_ter_rec', to='organizations.organizationlst')),
                ('is_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2manu_ter_rec', to=settings.AUTH_USER_MODEL)),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2manu_ter_rec', to='registrations.in_registrations')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2manu_ter_rec', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2manu_ter_rec', to=settings.AUTH_USER_MODEL)),
                ('store_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2manu_ter_rec', to='store_setup.store')),
            ],
        ),
        migrations.CreateModel(
            name='manual_return_receivedtl',
            fields=[
                ('manu_ret_rec_dtl_id', models.BigAutoField(default=8008588000000, editable=False, primary_key=True, serialize=False)),
                ('manu_ret_rec_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('manu_ret_rec_qty', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('dis_percentage', models.FloatField(blank=True, null=True)),
                ('item_batch', models.CharField(blank=True, max_length=150, null=True)),
                ('item_exp_date', models.DateField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1469400000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=674891000000, editable=False, null=True)),
                ('item_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2manu_ter_recDtl', to='item_setup.items')),
                ('manu_ret_rec_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manual_return_receive.manual_return_receive')),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2manu_ter_recDtl', to='registrations.in_registrations')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2manu_ter_recDtl', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2manu_ter_recDtl', to=settings.AUTH_USER_MODEL)),
                ('store_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2manu_ter_recDtl', to='store_setup.store')),
            ],
        ),
    ]
