# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_supplierdtl',
            fields=[
                ('supplierdtl_id', models.BigAutoField(default=1234010000000, editable=False, primary_key=True, serialize=False)),
                ('quotation_price', models.CharField(blank=True, max_length=100, null=True)),
                ('supp_sales_price', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=12370000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=11238000000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('item_id', models.BigAutoField(default=1233010000000, editable=False, primary_key=True, serialize=False)),
                ('item_no', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_price', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=100, null=True)),
                ('box_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('re_order_qty', models.IntegerField(blank=True, null=True)),
                ('discount_percentace', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_tk', models.CharField(blank=True, max_length=100, null=True)),
                ('extended_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_foreign_flag', models.BooleanField(default=False)),
                ('is_discount_able', models.BooleanField(default=False)),
                ('is_expireable', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1235000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112340000000, editable=False, null=True)),
            ],
        ),
    ]
