# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('others_setup', '0001_initial'),
        ('organizations', '0001_initial'),
        ('item_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_category2items', to='others_setup.item_category'),
        ),
        migrations.AddField(
            model_name='items',
            name='item_uom_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_uom2items', to='others_setup.item_uom'),
        ),
        migrations.AddField(
            model_name='items',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2items', to='organizations.organizationlst'),
        ),
    ]
