# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('others_setup', '0001_initial'),
        ('item_setup', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items',
            name='supplier_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2items', to='supplier_setup.suppliers'),
        ),
        migrations.AddField(
            model_name='items',
            name='type_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_type2items', to='others_setup.item_type'),
        ),
        migrations.AddField(
            model_name='item_supplierdtl',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_setup.items'),
        ),
        migrations.AddField(
            model_name='item_supplierdtl',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2item_supplierdtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_supplierdtl',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2item_supplierdtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_supplierdtl',
            name='supplier_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2item_supp', to='supplier_setup.suppliers'),
        ),
    ]
