# Generated by Django 4.1.5 on 2024-06-21 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_category',
            fields=[
                ('category_id', models.BigAutoField(default=123040000000, editable=False, primary_key=True, serialize=False)),
                ('category_no', models.CharField(blank=True, max_length=50, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1233000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112360000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_type',
            fields=[
                ('type_id', models.BigAutoField(default=123020000000, editable=False, primary_key=True, serialize=False)),
                ('type_no', models.CharField(blank=True, max_length=50, null=True)),
                ('type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1231000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112350000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_uom',
            fields=[
                ('item_uom_id', models.BigAutoField(default=123030000000, editable=False, primary_key=True, serialize=False)),
                ('item_uom_no', models.CharField(blank=True, max_length=50, null=True)),
                ('item_uom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1232000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112360000000, editable=False, null=True)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2item_uom', to='organizations.organizationlst')),
            ],
        ),
    ]
