# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('others_setup', '0001_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_uom',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2item_uom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_uom',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2item_uom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_type',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2item_type', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='item_type',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2item_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_type',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2item_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_category',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2item_category', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='item_category',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2item_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_category',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2item_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
