# Generated by Django 4.1.5 on 2024-10-26 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_setup', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_list', '0005_stock_lists_is_cancel_qty_stock_lists_lprdtl_id'),
        ('store_setup', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barcodes',
            fields=[
                ('bar_id', models.BigAutoField(default=190000000000, editable=False, primary_key=True, serialize=False)),
                ('barcode_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='barcode_image')),
                ('status', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(editable=False)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1990000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1999000000000, editable=False, null=True)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2barcodes', to='item_setup.items')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2barcodes', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2barcodes', to=settings.AUTH_USER_MODEL)),
                ('stock_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_id2barcodes', to='stock_list.stock_lists')),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2barcodes', to='store_setup.store')),
            ],
        ),
    ]
