# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash_on_hands',
            fields=[
                ('on_cash_id', models.BigAutoField(default=122122000000, editable=False, primary_key=True, serialize=False)),
                ('on_hand_cash', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='daily_bank_statement',
            fields=[
                ('deposit_id', models.BigAutoField(default=1555000000000, editable=False, primary_key=True, serialize=False)),
                ('deposits_amt', models.FloatField(blank=True, default=0)),
                ('types_deposit', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_methord', models.CharField(blank=True, max_length=50, null=True)),
                ('deposit_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1686000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=148830000000, editable=False, null=True)),
                ('bank_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_id2bankstatement', to='bank_setup.bank_lists')),
            ],
        ),
    ]
