# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_statement', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_bank_statement',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2bankstatement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daily_bank_statement',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2bankstatement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cash_on_hands',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2on_cash_hand', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='cash_on_hands',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2on_cash_hand', to='organizations.organizationlst'),
        ),
    ]
