# Generated by Django 4.1.5 on 2024-10-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_statement', '0004_daily_bank_statement_is_bank_statement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_on_hands',
            name='on_hand_cash',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
