# Generated by Django 4.1.5 on 2024-10-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branchslist_is_main_branch_branchslist_is_sub_branch'),
        ('bank_statement', '0005_alter_cash_on_hands_on_hand_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_bank_statement',
            name='main_branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_branch_id2bankstatement', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='daily_bank_statement',
            name='sub_branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_branch_id2bankstatement', to='organizations.branchslist'),
        ),
    ]
