# Generated by Django 4.1.5 on 2024-06-21 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departmentlst',
            fields=[
                ('dept_id', models.BigAutoField(default=101011000000, editable=False, primary_key=True, serialize=False)),
                ('dept_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_parent_dept', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dept_name', models.CharField(blank=True, max_length=200, null=True)),
                ('alias', models.CharField(blank=True, max_length=150, null=True)),
                ('level', models.CharField(blank=True, max_length=150, null=True)),
                ('Report_sl_no', models.CharField(blank=True, max_length=150, null=True)),
                ('financebusiness_area', models.CharField(blank=True, max_length=150, null=True)),
                ('unitflag_descr', models.CharField(blank=True, max_length=300, null=True)),
                ('ipd_dept_flag', models.BooleanField(default=False)),
                ('opd_dept_flag', models.BooleanField(default=False)),
                ('daycare_flag', models.BooleanField(default=False)),
                ('clinical_flag', models.BooleanField(default=False)),
                ('hr_flag', models.BooleanField(default=False)),
                ('film_required', models.BooleanField(default=False)),
                ('billing_flag', models.BooleanField(default=False)),
                ('dept_bill_activation', models.BooleanField(default=False)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('hotline', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_details_descr', models.CharField(blank=True, max_length=300, null=True)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1266770000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1266880000000, editable=False, null=True)),
            ],
        ),
    ]
