# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='local_purchase',
            fields=[
                ('lp_id', models.BigAutoField(default=2202022100000, editable=False, primary_key=True, serialize=False)),
                ('lp_no', models.CharField(editable=False, max_length=15)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('is_cash', models.BooleanField(default=False)),
                ('is_credit', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='', max_length=300)),
                ('cus_clients_name', models.CharField(blank=True, max_length=250, null=True)),
                ('cus_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cus_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('cus_emrg_person', models.CharField(blank=True, max_length=250, null=True)),
                ('cus_emrg_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('cus_address', models.CharField(blank=True, max_length=500, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1008888000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1009921000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='local_purchasedtl',
            fields=[
                ('lp_dtl_id', models.BigAutoField(default=1005555000000, editable=False, primary_key=True, serialize=False)),
                ('lp_rec_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('lp_rec_qty', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('dis_percentage', models.FloatField(blank=True, null=True)),
                ('item_batch', models.CharField(blank=True, max_length=150, null=True)),
                ('item_exp_date', models.DateField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1363400000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=334791000000, editable=False, null=True)),
                ('item_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2lp_recDtl', to='item_setup.items')),
                ('lp_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='without_grn_id', to='local_purchase.local_purchase')),
            ],
        ),
    ]
