# Generated by Django 4.1.5 on 2024-10-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0001_initial'),
        ('local_purchase', '0002_initial'),
        ('store_setup', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_purchasedtl',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2lp_recDtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='local_purchasedtl',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2lp_recDtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='local_purchasedtl',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2lp_recDtl', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2lp_rec', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='id_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2lp_rec', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='is_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2lp_rec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='reg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2lp_rec', to='registrations.in_registrations'),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2lp_rec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2lp_rec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='store_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2lp_rec', to='store_setup.store'),
        ),
    ]
