# Generated by Django 4.1.5 on 2024-10-19 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('local_purchase', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_purchase',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='is_returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2is_lpret_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='local_purchase',
            name='returned_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
