# Generated by Django 4.1.5 on 2024-11-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local_purchase', '0004_local_purchase_is_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_purchasedtl',
            name='lp_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='local_purchase.local_purchase'),
        ),
    ]
